name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Check if project directory exists
      run: if [ -d "project" ]; then cd project; else echo "Directory 'project' does not exist"; exit 1; fi
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
